#!/bin/bash
[ ! -d "$HOME/.dotfiles" ] && mv "../../dotfiles" "$HOME/.dotfiles"

ln -sf "$HOME/.dotfiles/gitconfig/gitalias.txt" "$HOME/gitalias.txt"

echo "inserting gitalias include... this does not check for existing configs"
echo "[include]" >> "$HOME/.gitconfig"
echo -e "\tpath = gitalias.txt" >> "$HOME/.gitconfig"
