#!/bin/bash
USER_HOME=$(eval echo ~${SUDO_USER})
[ -d "$USER_HOME/dotfiles" ] && mv "../../dotfiles" "$USER_HOME/.dotfiles"

echo "copy gitalias.txt"
yes | cp -f gitalias.txt "$USER_HOME/.gitalias.txt"

echo "git config include"
git config --global include.path ~/.gitalias.txt
git config --global alias.oldest-ancestor '!zsh -c '\''diff --old-line-format='' --new-line-format='' <(git rev-list --first-parent "${1:-master}") <(git rev-list --first-parent "${2:-HEAD}") | head -1'\'' -'

