#!/bin/bash
[ -d "$HOME/dotfiles" ] && mv "../../dotfiles" "$HOME/.dotfiles"

echo "copy gitalias.txt"
yes | cp -f gitalias.txt "$HOME/.gitalias.txt"

echo "git config include"
git config --global include.path ~/.gitalias.txt

