# espanso configuration file

toggle_key: OFF

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Dates
  - trigger: ":date"
    replace: "{{log}}"
    vars:
      - name: log
        type: date
        params:
          format: "%F"

  # todo
  - trigger: ":todo"
    replace: "// TODO: 박민규 {{date}} "
    vars:
      - name: date
        type: date
        params:
          format: "%F"
          
  # js console.log
  - trigger: ":log"
    replace: "console.log($|$)"
    
  # js console.debug
  - trigger: ":dbg"
    replace: "console.debug($|$)"
    
  # md frontmatter
  - trigger: ":fm"
    replace: "---\n
              title: '$|$'\n
              author: 'vlwkaos'\n
              created: {{date}}\n
              published: false\n
              ---\n"
    vars:
      - name: date
        type: date
        params:
          format: "%Y-%m-%d:%H:%M:%S"
          

  # md img insert 
  - trigger: ":img"
    replace: "<p align='center'>\n
              <img loading='lazy' src='$|$'/>\n
              <br><span>caption</span></p>"
              
  # md embed
  - trigger: ":embed"
    replace: "<div class='embed-wrapper'>$|$</div>"
