# espanso configuration file

toggle_key: OFF

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Dates
  - trigger: ":date"
    replace: "{{log}}"
    vars:
      - name: log
        type: date
        params:
          format: "%F"

  # todo
  - trigger: ":todo"
    replace: "TODO: 박민규 {{date}} "
    vars:
      - name: date
        type: date
        params:
          format: "%F"
          
  # js console.log
  - trigger: ":log"
    replace: "console.log($|$)"
    
  # js console.debug
  - trigger: ":dbg"
    replace: "console.debug($|$)"
    
  # md frontmatter
  - trigger: ":fm"
    replace: "---\ntitle: '$|$'\nauthor: 'vlwkaos'\ncreated: {{date}}\n---\n"
    vars:
      - name: date
        type: date
        params:
          format: "%Y-%m-%d:%H:%M:%S"

  # release notify
  - trigger: ":rls..."
    replace: "웹 {{form.deploytarget}} {{form.deployNumber}} 배포하겠습니다. \n버전: {{form.version}}\n시간: {{date}}\n내용: $|$"
    vars:
      - name: form
        type: form
        params:
          layout: |
            배포 타겟 {{deploytarget}} 
            배포 타겟 번호 {{deployNumber}}
            버전 {{version}}
          fields:
            deploytarget:
              type: list
              values:
                - 스테이징
                - 프로덕션
      - name: date
        type: date
        params:
          format: "%Y/%m/%d %H:%M:%S"
          
  # md embed
  - trigger: ":embed"
    replace: "<div class='embed-wrapper'>$|$</div>"
